import * as MediaLibrary from 'expo-media-library';
import { createUser, createCategory, createPost } from './CRUDFunctions';

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//user dummy part

export const STATUSS = {
  LOGIN: 0,
  LOGOUT: 1,
};

export const getLocalPhotos = async () => {
  const options = {
    first: 4,
    sortBy: [MediaLibrary.SortBy.creationTime],
  };
  const res = await MediaLibrary.getAssetsAsync(options);
  if ((res = null)) return null;

  return res;
};

const TIME_ZONE = 9 * 60 * 60 * 1000; // 9시간

const date = new Date();

var currentTime = new Date(date.getTime() + TIME_ZONE)
  .toISOString()
  .replace('T', ' ')
  .slice(0, -5)
  .toString();

export const users = [
  {
    userTableID: 1,
    userID: '정재훈',
    password: 1234,
    created: currentTime,
    phoneNumber: '01012345678',
    statuss: STATUSS.LOGIN,
    updated: currentTime,
    userImage: getLocalPhotos[0],
    userName: '정재훈',
    favoritePostID: [1, 30, 50, 77],
  },
  {
    userTableID: 2,
    userID: '가순원',
    password: 1234,
    created: currentTime,
    phoneNumber: '01022345678',
    statuss: STATUSS.LOGIN,
    updated: currentTime,
    userImage: getLocalPhotos[1],
    userName: '가순원',
    favoritePostID: [3, 8, 60, 75],
  },
  {
    userTableID: 3,
    userID: '김상원',
    password: 1234,
    created: currentTime,
    phoneNumber: '01032345678',
    statuss: STATUSS.LOGIN,
    updated: currentTime,
    userImage: getLocalPhotos[2],
    userName: '김상원',
    favoritePostID: [11, 37, 60, 87],
  },
  {
    userTableID: 4,
    userID: '김재영',
    password: 1234,
    created: currentTime,
    phoneNumber: '01042345678',
    statuss: STATUSS.LOGIN,
    updated: currentTime,
    userImage: getLocalPhotos[3],
    userName: '김재영',
    favoritePostID: [9, 40, 80, 87],
  },
];
export const UserCreateSet = (user) => {
  const formdata = new FormData();
  formdata.append('userID', user.userID);
  formdata.append('userTableID', user.userTableID);
  formdata.append('password', user.password);
  formdata.append('created', user.created);
  formdata.append('phoneNumber', user.phoneNumber);
  formdata.append('statuss', user.statuss);
  formdata.append('updated', user.updated);
  formdata.append('userImage', user.userImage);
  formdata.append('userName', user.userName);
  formdata.append('favoritePostID', user.favoritePostID);
  return formdata;
};

export const userMade = (userNumber) => {
  for (var n = 0; n < userNumber; n++) {
    createUser(UserCreateSet(users[n]));
  }
};
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//category dummy part
export const categories = [
  {
    categoryID: 1,
    categoryGroup: 'A',
    categoryLevel: 1,
    categoryName: '디지털기기',
    categoryParent: 0,
  },
  {
    categoryID: 2,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: 'TV/영상가전',
    categoryParent: 1,
  },
  {
    categoryID: 3,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'TV',
    categoryParent: 2,
  },
  {
    categoryID: 4,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '미러링/스트리밍',
    categoryParent: 2,
  },
  {
    categoryID: 5,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'TV악세서리',
    categoryParent: 2,
  },
  {
    categoryID: 6,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '빔/프로젝터 /스크린',
    categoryParent: 2,
  },
  {
    categoryID: 7,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '냉장고',
    categoryParent: 1,
  },
  {
    categoryID: 8,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '일반냉장고',
    categoryParent: 7,
  },
  {
    categoryID: 9,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '미니냉장고',
    categoryParent: 7,
  },
  {
    categoryID: 10,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '김치냉장고',
    categoryParent: 7,
  },
  {
    categoryID: 11,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '냉동고',
    categoryParent: 7,
  },
  {
    categoryID: 12,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '전용냉장고',
    categoryParent: 7,
  },
  {
    categoryID: 13,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '3/4도어냉장고',
    categoryParent: 7,
  },
  {
    categoryID: 14,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '세탁기/건조기',
    categoryParent: 1,
  },
  {
    categoryID: 15,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '세탁기건조기세트',
    categoryParent: 14,
  },
  {
    categoryID: 16,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '세탁기',
    categoryParent: 14,
  },
  {
    categoryID: 17,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '건조기',
    categoryParent: 14,
  },
  {
    categoryID: 18,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '의류관리기',
    categoryParent: 14,
  },
  {
    categoryID: 19,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '악세서리',
    categoryParent: 14,
  },
  {
    categoryID: 20,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '생활가전',
    categoryParent: 1,
  },
  {
    categoryID: 21,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '다리미/재봉/보풀',
    categoryParent: 20,
  },
  {
    categoryID: 22,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '도어록/비디오폰',
    categoryParent: 20,
  },
  {
    categoryID: 23,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '비데/온수기',
    categoryParent: 20,
  },
  {
    categoryID: 24,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '전동칫솔/살균기',
    categoryParent: 20,
  },
  {
    categoryID: 25,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '청소기',
    categoryParent: 1,
  },
  {
    categoryID: 26,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '먼지비움청소기',
    categoryParent: 25,
  },
  {
    categoryID: 27,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '스틱청소기',
    categoryParent: 25,
  },
  {
    categoryID: 28,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '진공청소기',
    categoryParent: 25,
  },
  {
    categoryID: 29,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '로봇청소기',
    categoryParent: 25,
  },
  {
    categoryID: 30,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '물걸레청소기',
    categoryParent: 25,
  },
  {
    categoryID: 31,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '기타청소기',
    categoryParent: 25,
  },
  {
    categoryID: 32,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '필터/악세서리',
    categoryParent: 25,
  },
  {
    categoryID: 33,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '계절가전',
    categoryParent: 1,
  },
  {
    categoryID: 34,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '공기청정기',
    categoryParent: 33,
  },
  {
    categoryID: 35,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '선풍기',
    categoryParent: 33,
  },
  {
    categoryID: 36,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '에어컨',
    categoryParent: 33,
  },
  {
    categoryID: 37,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '제습기',
    categoryParent: 33,
  },
  {
    categoryID: 38,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '냉풍기',
    categoryParent: 33,
  },
  {
    categoryID: 39,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '모기/해충퇴치기',
    categoryParent: 33,
  },
  {
    categoryID: 40,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '가습기/에어워셔',
    categoryParent: 33,
  },
  {
    categoryID: 41,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '냉온수매트',
    categoryParent: 33,
  },
  {
    categoryID: 42,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '뷰티/헤어가전',
    categoryParent: 1,
  },
  {
    categoryID: 43,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '헤어드라이어',
    categoryParent: 42,
  },
  {
    categoryID: 44,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '고데기/매직기',
    categoryParent: 42,
  },
  {
    categoryID: 45,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '두피/헤어관리',
    categoryParent: 42,
  },
  {
    categoryID: 46,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '피부관리기기',
    categoryParent: 42,
  },
  {
    categoryID: 47,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '면도기/이발기',
    categoryParent: 42,
  },
  {
    categoryID: 48,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '제모기',
    categoryParent: 42,
  },
  {
    categoryID: 49,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '건강가전',
    categoryParent: 1,
  },
  {
    categoryID: 50,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '안마의자',
    categoryParent: 49,
  },
  {
    categoryID: 51,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '안마/찜질기',
    categoryParent: 49,
  },
  {
    categoryID: 52,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '구강가전',
    categoryParent: 49,
  },
  {
    categoryID: 53,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '의료기기',
    categoryParent: 49,
  },
  {
    categoryID: 54,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '살균/소독',
    categoryParent: 49,
  },
  {
    categoryID: 55,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '주방가전',
    categoryParent: 1,
  },
  {
    categoryID: 56,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '전기밥솥',
    categoryParent: 55,
  },
  {
    categoryID: 57,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '전자레인지',
    categoryParent: 55,
  },
  {
    categoryID: 58,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '오븐',
    categoryParent: 55,
  },
  {
    categoryID: 59,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '가스레인지',
    categoryParent: 55,
  },
  {
    categoryID: 60,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '식기세척/건조기',
    categoryParent: 55,
  },
  {
    categoryID: 61,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '믹서기',
    categoryParent: 55,
  },
  {
    categoryID: 62,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '커피머신',
    categoryParent: 55,
  },
  {
    categoryID: 63,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '전기포트',
    categoryParent: 55,
  },
  {
    categoryID: 64,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '튀김기',
    categoryParent: 55,
  },
  {
    categoryID: 65,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '토스터',
    categoryParent: 55,
  },
  {
    categoryID: 66,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '노트북',
    categoryParent: 1,
  },
  {
    categoryID: 67,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '삼성',
    categoryParent: 66,
  },
  {
    categoryID: 68,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'LG전자',
    categoryParent: 66,
  },
  {
    categoryID: 69,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'Apple',
    categoryParent: 66,
  },
  {
    categoryID: 70,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'Lenovo',
    categoryParent: 66,
  },
  {
    categoryID: 71,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'hp',
    categoryParent: 66,
  },
  {
    categoryID: 72,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'msi',
    categoryParent: 66,
  },
  {
    categoryID: 73,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'MicrosoftSurface',
    categoryParent: 66,
  },
  {
    categoryID: 74,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '한성컴퓨터',
    categoryParent: 66,
  },
  {
    categoryID: 75,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'DELL',
    categoryParent: 66,
  },
  {
    categoryID: 76,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'GIGABYTE',
    categoryParent: 66,
  },
  {
    categoryID: 77,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'acer',
    categoryParent: 66,
  },
  {
    categoryID: 78,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'intel',
    categoryParent: 66,
  },
  {
    categoryID: 79,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '기타 브랜드',
    categoryParent: 66,
  },
  {
    categoryID: 80,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '데스크탑',
    categoryParent: 1,
  },
  {
    categoryID: 81,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '브랜드PC',
    categoryParent: 80,
  },
  {
    categoryID: 82,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '일체형PC',
    categoryParent: 80,
  },
  {
    categoryID: 83,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '조립PC',
    categoryParent: 80,
  },
  {
    categoryID: 84,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '미니PC',
    categoryParent: 80,
  },
  {
    categoryID: 85,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '휴대폰',
    categoryParent: 1,
  },
  {
    categoryID: 86,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'Apple',
    categoryParent: 85,
  },
  {
    categoryID: 87,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '삼성전자',
    categoryParent: 85,
  },
  {
    categoryID: 88,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '갤럭시',
    categoryParent: 85,
  },
  {
    categoryID: 89,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '샤오미',
    categoryParent: 85,
  },
  {
    categoryID: 90,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '2G',
    categoryParent: 85,
  },
  {
    categoryID: 91,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '기타',
    categoryParent: 85,
  },
  {
    categoryID: 92,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '핸드폰 악세서리',
    categoryParent: 85,
  },
  {
    categoryID: 93,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '태블릿PC',
    categoryParent: 1,
  },
  {
    categoryID: 94,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '삼성',
    categoryParent: 93,
  },
  {
    categoryID: 95,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'LG전자',
    categoryParent: 93,
  },
  {
    categoryID: 96,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'Apple',
    categoryParent: 93,
  },
  {
    categoryID: 97,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'Lenovo',
    categoryParent: 93,
  },
  {
    categoryID: 98,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '태클라스트',
    categoryParent: 93,
  },
  {
    categoryID: 99,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '아이뮤즈',
    categoryParent: 93,
  },
  {
    categoryID: 100,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '샤론6',
    categoryParent: 93,
  },
  {
    categoryID: 101,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: 'EKASN',
    categoryParent: 93,
  },
  {
    categoryID: 102,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '머큐리',
    categoryParent: 93,
  },
  {
    categoryID: 103,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '악세서리',
    categoryParent: 93,
  },
  {
    categoryID: 104,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '스마트워치/밴드',
    categoryParent: 1,
  },
  {
    categoryID: 105,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '스마트워치',
    categoryParent: 104,
  },
  {
    categoryID: 106,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '스마트밴드',
    categoryParent: 104,
  },
  {
    categoryID: 107,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '악세서리',
    categoryParent: 104,
  },
  {
    categoryID: 108,
    categoryGroup: 'A',
    categoryLevel: 2,
    categoryName: '게임',
    categoryParent: 1,
  },
  {
    categoryID: 109,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '게이밍노트북',
    categoryParent: 108,
  },
  {
    categoryID: 110,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '게이밍데스크탑',
    categoryParent: 108,
  },
  {
    categoryID: 111,
    categoryGroup: 'A',
    categoryLevel: 3,
    categoryName: '게이밍모니터',
    categoryParent: 108,
  },
  {
    categoryID: 112,
    categoryGroup: 'B',
    categoryLevel: 1,
    categoryName: '가구/인테리어',
    categoryParent: 0,
  },
  {
    categoryID: 113,
    categoryGroup: 'B',
    categoryLevel: 2,
    categoryName: '가구 ',
    categoryParent: 112,
  },
  {
    categoryID: 114,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '소파',
    categoryParent: 113,
  },
  {
    categoryID: 115,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '침대',
    categoryParent: 113,
  },
  {
    categoryID: 116,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '테이블/의자',
    categoryParent: 113,
  },
  {
    categoryID: 117,
    categoryGroup: 'B',
    categoryLevel: 2,
    categoryName: '인테리어',
    categoryParent: 112,
  },
  {
    categoryID: 118,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '디퓨저/방향제',
    categoryParent: 117,
  },
  {
    categoryID: 119,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '시계',
    categoryParent: 117,
  },
  {
    categoryID: 120,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '거울',
    categoryParent: 117,
  },
  {
    categoryID: 121,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '액자',
    categoryParent: 117,
  },
  {
    categoryID: 122,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '그림/사진',
    categoryParent: 117,
  },
  {
    categoryID: 123,
    categoryGroup: 'B',
    categoryLevel: 3,
    categoryName: '시트지/스티커',
    categoryParent: 117,
  },
  {
    categoryID: 124,
    categoryGroup: 'C',
    categoryLevel: 1,
    categoryName: '어린이/아기',
    categoryParent: 0,
  },
  {
    categoryID: 125,
    categoryGroup: 'C',
    categoryLevel: 2,
    categoryName: '유아용품',
    categoryParent: 124,
  },
  {
    categoryID: 126,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '유아의류',
    categoryParent: 125,
  },
  {
    categoryID: 127,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '기저귀',
    categoryParent: 125,
  },
  {
    categoryID: 128,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '물티슈',
    categoryParent: 125,
  },
  {
    categoryID: 129,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '이유식',
    categoryParent: 125,
  },
  {
    categoryID: 130,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '분유',
    categoryParent: 125,
  },
  {
    categoryID: 131,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '장난감',
    categoryParent: 125,
  },
  {
    categoryID: 132,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '게임기',
    categoryParent: 125,
  },
  {
    categoryID: 133,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '기타 유아용품',
    categoryParent: 125,
  },
  {
    categoryID: 134,
    categoryGroup: 'C',
    categoryLevel: 2,
    categoryName: '홈인테리어',
    categoryParent: 124,
  },
  {
    categoryID: 135,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '카페트',
    categoryParent: 134,
  },
  {
    categoryID: 136,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '세탁/청소용품',
    categoryParent: 134,
  },
  {
    categoryID: 137,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '유아가구',
    categoryParent: 134,
  },
  {
    categoryID: 138,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '유아침구',
    categoryParent: 134,
  },
  {
    categoryID: 139,
    categoryGroup: 'C',
    categoryLevel: 3,
    categoryName: '안전용품',
    categoryParent: 134,
  },
  {
    categoryID: 140,
    categoryGroup: 'D',
    categoryLevel: 1,
    categoryName: '패션',
    categoryParent: 0,
  },
  {
    categoryID: 141,
    categoryGroup: 'D',
    categoryLevel: 2,
    categoryName: '여성의류',
    categoryParent: 140,
  },
  {
    categoryID: 142,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '상의',
    categoryParent: 141,
  },
  {
    categoryID: 143,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '원피스',
    categoryParent: 141,
  },
  {
    categoryID: 144,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '하의',
    categoryParent: 141,
  },
  {
    categoryID: 145,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '치마',
    categoryParent: 141,
  },
  {
    categoryID: 146,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '신발',
    categoryParent: 141,
  },
  {
    categoryID: 147,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '여성악세서리',
    categoryParent: 141,
  },
  {
    categoryID: 148,
    categoryGroup: 'D',
    categoryLevel: 2,
    categoryName: '남성의류',
    categoryParent: 140,
  },
  {
    categoryID: 149,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '상의',
    categoryParent: 148,
  },
  {
    categoryID: 150,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '하의',
    categoryParent: 148,
  },
  {
    categoryID: 151,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '신발',
    categoryParent: 148,
  },
  {
    categoryID: 152,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '남성악세서리',
    categoryParent: 148,
  },
  {
    categoryID: 153,
    categoryGroup: 'D',
    categoryLevel: 2,
    categoryName: '뷰티 ',
    categoryParent: 140,
  },
  {
    categoryID: 154,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '스킨케어',
    categoryParent: 153,
  },
  {
    categoryID: 155,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '메이크업',
    categoryParent: 153,
  },
  {
    categoryID: 156,
    categoryGroup: 'D',
    categoryLevel: 3,
    categoryName: '향수',
    categoryParent: 153,
  },
  {
    categoryID: 157,
    categoryGroup: 'E',
    categoryLevel: 1,
    categoryName: '스포츠/레저',
    categoryParent: 0,
  },
  {
    categoryID: 158,
    categoryGroup: 'E',
    categoryLevel: 2,
    categoryName: '스포츠장비',
    categoryParent: 157,
  },
  {
    categoryID: 159,
    categoryGroup: 'E',
    categoryLevel: 3,
    categoryName: '피트니스 장비',
    categoryParent: 158,
  },
  {
    categoryID: 160,
    categoryGroup: 'E',
    categoryLevel: 3,
    categoryName: '캠핑장비',
    categoryParent: 158,
  },
  {
    categoryID: 161,
    categoryGroup: 'E',
    categoryLevel: 3,
    categoryName: '자전거',
    categoryParent: 158,
  },
  {
    categoryID: 162,
    categoryGroup: 'E',
    categoryLevel: 2,
    categoryName: '운동복',
    categoryParent: 157,
  },
  {
    categoryID: 163,
    categoryGroup: 'E',
    categoryLevel: 3,
    categoryName: '기능성의류',
    categoryParent: 162,
  },
  {
    categoryID: 164,
    categoryGroup: 'E',
    categoryLevel: 3,
    categoryName: '운동화',
    categoryParent: 162,
  },
  {
    categoryID: 165,
    categoryGroup: 'E',
    categoryLevel: 3,
    categoryName: '수영복',
    categoryParent: 162,
  },
  {
    categoryID: 166,
    categoryGroup: 'F',
    categoryLevel: 1,
    categoryName: '중고차/자동차',
    categoryParent: 0,
  },
  {
    categoryID: 167,
    categoryGroup: 'F',
    categoryLevel: 2,
    categoryName: '중고차 ',
    categoryParent: 166,
  },
  {
    categoryID: 168,
    categoryGroup: 'F',
    categoryLevel: 3,
    categoryName: '세단',
    categoryParent: 167,
  },
  {
    categoryID: 169,
    categoryGroup: 'F',
    categoryLevel: 3,
    categoryName: 'SUV',
    categoryParent: 167,
  },
  {
    categoryID: 170,
    categoryGroup: 'F',
    categoryLevel: 3,
    categoryName: '트럭',
    categoryParent: 167,
  },
  {
    categoryID: 171,
    categoryGroup: 'F',
    categoryLevel: 2,
    categoryName: '부품/악세서리',
    categoryParent: 166,
  },
  {
    categoryID: 172,
    categoryGroup: 'F',
    categoryLevel: 3,
    categoryName: '타이어',
    categoryParent: 171,
  },
  {
    categoryID: 173,
    categoryGroup: 'F',
    categoryLevel: 3,
    categoryName: '휠',
    categoryParent: 171,
  },
  {
    categoryID: 174,
    categoryGroup: 'F',
    categoryLevel: 3,
    categoryName: '전자장치',
    categoryParent: 171,
  },
  {
    categoryID: 175,
    categoryGroup: 'F',
    categoryLevel: 3,
    categoryName: '외부 액세서리',
    categoryParent: 171,
  },
  {
    categoryID: 176,
    categoryGroup: 'G',
    categoryLevel: 1,
    categoryName: '도서 및 미디어',
    categoryParent: 0,
  },
  {
    categoryID: 177,
    categoryGroup: 'G',
    categoryLevel: 2,
    categoryName: '책',
    categoryParent: 176,
  },
  {
    categoryID: 178,
    categoryGroup: 'G',
    categoryLevel: 3,
    categoryName: '소설',
    categoryParent: 177,
  },
  {
    categoryID: 179,
    categoryGroup: 'G',
    categoryLevel: 3,
    categoryName: '논픽션',
    categoryParent: 177,
  },
  {
    categoryID: 180,
    categoryGroup: 'G',
    categoryLevel: 3,
    categoryName: '아동도서',
    categoryParent: 177,
  },
  {
    categoryID: 181,
    categoryGroup: 'G',
    categoryLevel: 3,
    categoryName: '기타도서',
    categoryParent: 177,
  },
  {
    categoryID: 182,
    categoryGroup: 'G',
    categoryLevel: 2,
    categoryName: '영화 및 음악',
    categoryParent: 176,
  },
  {
    categoryID: 183,
    categoryGroup: 'G',
    categoryLevel: 3,
    categoryName: 'DVD/블루레이',
    categoryParent: 182,
  },
  {
    categoryID: 184,
    categoryGroup: 'G',
    categoryLevel: 3,
    categoryName: 'CD',
    categoryParent: 182,
  },
  {
    categoryID: 185,
    categoryGroup: 'G',
    categoryLevel: 3,
    categoryName: '기타 악세서리',
    categoryParent: 182,
  },
];

export const CategoryCreateSet = (category) => {
  const formdata = new FormData();
  formdata.append('categoryID', category.categoryID);
  formdata.append('categoryGroup', category.categoryGroup);
  formdata.append('categoryLevel', category.categoryLevel);
  formdata.append('categoryName', category.categoryName);
  formdata.append('categoryParent', category.categoryParent);
  return formdata;
};

export const categoryMade = () => {
  const TIME_ZONE = 9 * 60 * 60 * 1000; // 9시간

  const date = new Date();

  var currentTime = new Date(date.getTime() + TIME_ZONE)
    .toISOString()
    .replace('T', ' ')
    .slice(0, -5)
    .toString();

  for (var n = 0; n < 185; n++) {
    createCategory(CategoryCreateSet(categories[n]));
  }
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//post dummy part
/*
generateSite:
https://app.json-generator.com/ALI1ds_X1g1P
generateCode:
JG.repeat(100, 100, {
  postID:null ,
  created:JG.date(new Date(2010, 0, 1), new Date(2015, 0, 1)),
  postContent:JG.loremIpsum({ units: 'sentences', count: 2 }),
  postCost:JG.integer(1000,100000,1000),
  postDealDone:JG.bool(),
  postImage:null,
  postTitle:JG.loremIpsum({ units: 'words', count: 2 }),
  statuss:JG.random(0,1),
  townID:JG.integer(1,20),
  updated:JG.date(new Date(2016, 0, 1), new Date(2023, 0, 1)),
  categoryID:JG.integer(1,185),
  userTableID:JG.integer(1,4)
});
*/
export const posts = [
  {
    postID: null,
    created: '2014-04-27T06:03:42.584Z',
    postContent:
      'Mollit elit duis veniam commodo deserunt reprehenderit ex sint aliquip. Ex fugiat amet in minim mollit tempor incididunt sunt non.',
    postCost: 6700,
    postDealDone: false,
    postImage: null,
    postTitle: 'amet laborum',
    statuss: 1,
    townID: 1,
    updated: '2021-08-13T03:20:46.798Z',
    categoryID: 38,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-09-18T23:23:25.886Z',
    postContent:
      'Culpa ex id ullamco culpa sint ut consequat elit laborum nulla officia. Enim et labore ea dolore ad tempor ea commodo Lorem.',
    postCost: 96318,
    postDealDone: false,
    postImage: null,
    postTitle: 'veniam dolore',
    statuss: 0,
    townID: 5,
    updated: '2018-09-18T10:57:49.223Z',
    categoryID: 140,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-03-12T11:02:05.534Z',
    postContent:
      'Proident est pariatur magna aute labore adipisicing elit velit voluptate. Deserunt enim sit consequat anim ex cillum enim quis amet labore.',
    postCost: 95196,
    postDealDone: true,
    postImage: null,
    postTitle: 'eiusmod deserunt',
    statuss: 0,
    townID: 5,
    updated: '2017-10-17T17:34:20.717Z',
    categoryID: 90,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-05-09T05:44:46.412Z',
    postContent:
      'Ad tempor enim duis elit aliqua ex culpa magna proident incididunt consequat incididunt. Esse magna commodo deserunt mollit voluptate ullamco irure.',
    postCost: 48656,
    postDealDone: true,
    postImage: null,
    postTitle: 'consectetur aute',
    statuss: 1,
    townID: 10,
    updated: '2018-08-10T11:53:08.604Z',
    categoryID: 178,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2010-08-31T03:36:45.459Z',
    postContent:
      'Amet proident officia cillum pariatur. Elit commodo occaecat nostrud occaecat aliquip proident aute ipsum sunt est.',
    postCost: 13460,
    postDealDone: true,
    postImage: null,
    postTitle: 'commodo culpa',
    statuss: 1,
    townID: 9,
    updated: '2018-11-04T21:28:57.883Z',
    categoryID: 51,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2010-09-12T16:57:31.518Z',
    postContent:
      'Non Lorem est duis esse mollit consectetur aliquip sit minim deserunt sint. Elit non eu consectetur nostrud cupidatat eu eiusmod veniam dolore quis sint adipisicing amet ullamco.',
    postCost: 65015,
    postDealDone: true,
    postImage: null,
    postTitle: 'do voluptate',
    statuss: 1,
    townID: 10,
    updated: '2017-10-21T06:19:06.997Z',
    categoryID: 72,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2012-07-07T06:19:45.249Z',
    postContent:
      'Ex mollit exercitation nisi adipisicing amet ex voluptate esse excepteur dolore occaecat. Aute Lorem nulla laborum dolor dolore ipsum et elit proident ex irure qui sint minim.',
    postCost: 16218,
    postDealDone: true,
    postImage: null,
    postTitle: 'consectetur ex',
    statuss: 1,
    townID: 15,
    updated: '2018-12-11T04:05:06.690Z',
    categoryID: 113,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-10-15T13:26:48.224Z',
    postContent:
      'Magna Lorem laboris duis magna cupidatat irure pariatur cupidatat aliquip quis tempor pariatur. Minim ipsum aliqua aliqua nostrud.',
    postCost: 78939,
    postDealDone: false,
    postImage: null,
    postTitle: 'nisi dolore',
    statuss: 1,
    townID: 5,
    updated: '2017-12-27T15:30:56.513Z',
    categoryID: 4,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2012-10-07T10:44:45.180Z',
    postContent:
      'Culpa id minim cupidatat irure ad et nulla cillum quis eiusmod excepteur sunt. Fugiat in sunt quis culpa ullamco minim sit sit nisi cupidatat id sint id ullamco.',
    postCost: 18715,
    postDealDone: false,
    postImage: null,
    postTitle: 'excepteur do',
    statuss: 0,
    townID: 13,
    updated: '2018-02-01T14:48:49.108Z',
    categoryID: 39,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2011-10-14T00:15:19.332Z',
    postContent:
      'Reprehenderit voluptate amet quis ad incididunt occaecat. Ullamco mollit incididunt anim ea incididunt ad.',
    postCost: 4270,
    postDealDone: true,
    postImage: null,
    postTitle: 'laborum incididunt',
    statuss: 0,
    townID: 3,
    updated: '2019-05-12T21:17:21.258Z',
    categoryID: 32,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2014-03-03T23:08:57.101Z',
    postContent:
      'Reprehenderit est aute est ut velit laborum consequat labore Lorem excepteur. Incididunt velit amet dolore ipsum tempor do excepteur aliqua minim esse mollit exercitation pariatur incididunt.',
    postCost: 88156,
    postDealDone: true,
    postImage: null,
    postTitle: 'laboris proident',
    statuss: 1,
    townID: 20,
    updated: '2022-03-23T11:39:25.699Z',
    categoryID: 47,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-12-17T21:42:15.532Z',
    postContent:
      'Quis ut anim minim ex reprehenderit. Magna tempor consectetur eu sint non duis mollit.',
    postCost: 83574,
    postDealDone: true,
    postImage: null,
    postTitle: 'sit adipisicing',
    statuss: 0,
    townID: 9,
    updated: '2020-12-11T23:58:36.484Z',
    categoryID: 88,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2011-08-11T22:11:12.117Z',
    postContent:
      'Excepteur excepteur voluptate in Lorem dolore ea nulla eiusmod non eiusmod. Nisi eu do mollit deserunt eiusmod ullamco.',
    postCost: 67807,
    postDealDone: true,
    postImage: null,
    postTitle: 'ad Lorem',
    statuss: 1,
    townID: 12,
    updated: '2020-12-05T21:29:11.433Z',
    categoryID: 148,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2012-11-23T21:18:56.622Z',
    postContent:
      'Aliqua minim ad laboris qui anim fugiat ullamco sint qui ipsum incididunt cillum irure. Consequat id ullamco anim et nulla excepteur non sint cillum aliquip.',
    postCost: 90370,
    postDealDone: true,
    postImage: null,
    postTitle: 'minim labore',
    statuss: 1,
    townID: 2,
    updated: '2018-11-01T01:35:09.013Z',
    categoryID: 158,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2011-03-31T16:39:27.127Z',
    postContent:
      'Occaecat qui minim quis laboris tempor enim esse do do dolor nisi. Consequat proident ea mollit laborum quis tempor proident laborum occaecat.',
    postCost: 79212,
    postDealDone: false,
    postImage: null,
    postTitle: 'aute Lorem',
    statuss: 1,
    townID: 8,
    updated: '2021-02-27T20:54:51.102Z',
    categoryID: 75,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2013-12-08T10:30:23.152Z',
    postContent:
      'Enim labore nulla ad nulla non nisi esse incididunt consectetur elit. Nostrud non est incididunt labore amet cillum ullamco occaecat dolore non.',
    postCost: 29719,
    postDealDone: true,
    postImage: null,
    postTitle: 'do pariatur',
    statuss: 0,
    townID: 1,
    updated: '2019-11-05T09:56:29.077Z',
    categoryID: 141,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-02-06T17:07:28.688Z',
    postContent:
      'Magna minim in exercitation laboris occaecat sunt in. Laboris deserunt qui non nisi sint mollit.',
    postCost: 38369,
    postDealDone: false,
    postImage: null,
    postTitle: 'mollit labore',
    statuss: 1,
    townID: 2,
    updated: '2018-07-29T14:20:58.170Z',
    categoryID: 16,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2011-11-17T01:21:58.605Z',
    postContent:
      'Irure nisi consequat adipisicing sint labore id. Cillum quis enim non ex deserunt deserunt.',
    postCost: 71986,
    postDealDone: true,
    postImage: null,
    postTitle: 'aliquip aliquip',
    statuss: 1,
    townID: 8,
    updated: '2019-05-14T11:28:09.907Z',
    categoryID: 57,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2013-12-18T17:59:17.909Z',
    postContent:
      'Aliquip nostrud cillum fugiat eu quis fugiat duis excepteur ea duis incididunt id. Consequat occaecat Lorem irure tempor.',
    postCost: 52515,
    postDealDone: false,
    postImage: null,
    postTitle: 'in dolor',
    statuss: 1,
    townID: 3,
    updated: '2016-05-01T03:14:21.206Z',
    categoryID: 171,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2012-03-10T10:44:19.052Z',
    postContent:
      'Non consectetur consectetur elit pariatur veniam non officia deserunt irure ex ipsum elit. Lorem consectetur aliqua incididunt ad est consectetur ex ex.',
    postCost: 64943,
    postDealDone: true,
    postImage: null,
    postTitle: 'Lorem ut',
    statuss: 1,
    townID: 2,
    updated: '2019-09-01T06:07:30.778Z',
    categoryID: 21,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2012-06-07T01:31:21.513Z',
    postContent:
      'Ea pariatur dolor ex voluptate. Do ex velit consectetur culpa sit magna esse tempor sit.',
    postCost: 81109,
    postDealDone: false,
    postImage: null,
    postTitle: 'incididunt ea',
    statuss: 0,
    townID: 2,
    updated: '2021-01-08T06:32:31.598Z',
    categoryID: 158,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-02-09T10:35:52.393Z',
    postContent:
      'Aute tempor voluptate commodo adipisicing sint sunt dolor velit ea commodo. Nulla velit minim et veniam.',
    postCost: 88363,
    postDealDone: true,
    postImage: null,
    postTitle: 'eu qui',
    statuss: 0,
    townID: 15,
    updated: '2018-11-30T21:22:18.032Z',
    categoryID: 53,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-08-04T20:54:37.512Z',
    postContent:
      'Labore ipsum mollit aliquip culpa ut consequat Lorem quis voluptate elit proident nisi cillum. Consectetur laboris dolor nisi sit aliquip aute anim ut voluptate laboris velit cillum.',
    postCost: 99502,
    postDealDone: true,
    postImage: null,
    postTitle: 'anim anim',
    statuss: 0,
    townID: 18,
    updated: '2021-04-21T23:15:15.254Z',
    categoryID: 148,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2011-02-19T13:04:19.172Z',
    postContent:
      'Laboris excepteur sunt occaecat non consequat incididunt sint cillum Lorem. Voluptate pariatur labore qui do nostrud mollit non.',
    postCost: 88446,
    postDealDone: true,
    postImage: null,
    postTitle: 'officia enim',
    statuss: 1,
    townID: 5,
    updated: '2016-07-24T14:03:51.608Z',
    categoryID: 35,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2010-08-03T12:24:44.859Z',
    postContent:
      'Deserunt officia consequat duis nostrud sit reprehenderit aliqua ipsum incididunt pariatur voluptate non velit nisi. Minim anim elit sint nisi laboris cillum.',
    postCost: 88478,
    postDealDone: true,
    postImage: null,
    postTitle: 'dolor cillum',
    statuss: 1,
    townID: 2,
    updated: '2021-11-28T02:52:48.682Z',
    categoryID: 88,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-04-10T12:37:07.988Z',
    postContent:
      'Ipsum id elit sunt elit eiusmod. Esse ipsum elit Lorem culpa.',
    postCost: 35816,
    postDealDone: false,
    postImage: null,
    postTitle: 'occaecat nisi',
    statuss: 0,
    townID: 3,
    updated: '2020-06-18T10:13:38.261Z',
    categoryID: 60,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2014-07-02T11:39:18.065Z',
    postContent:
      'Aliquip aliqua reprehenderit elit commodo id sunt nisi cillum amet. Magna ad mollit ea occaecat laborum amet esse amet ipsum elit sint proident quis.',
    postCost: 54412,
    postDealDone: false,
    postImage: null,
    postTitle: 'est consectetur',
    statuss: 0,
    townID: 12,
    updated: '2017-03-25T03:10:35.648Z',
    categoryID: 152,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2013-11-24T03:26:39.939Z',
    postContent:
      'Sit labore cillum aute excepteur. Sint Lorem do elit aute Lorem nostrud culpa sint non dolor occaecat.',
    postCost: 70314,
    postDealDone: true,
    postImage: null,
    postTitle: 'ea dolore',
    statuss: 0,
    townID: 7,
    updated: '2017-10-19T07:45:45.587Z',
    categoryID: 167,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2010-03-23T13:26:09.610Z',
    postContent:
      'Dolore velit voluptate velit nulla ullamco proident aute. Laborum laboris nisi commodo ut anim minim.',
    postCost: 59071,
    postDealDone: true,
    postImage: null,
    postTitle: 'Lorem aliqua',
    statuss: 0,
    townID: 10,
    updated: '2016-01-11T11:25:26.386Z',
    categoryID: 93,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2010-01-01T08:51:22.338Z',
    postContent:
      'Laborum ullamco occaecat officia eu dolore veniam dolore tempor voluptate in dolor adipisicing. Duis fugiat aute do est sunt culpa.',
    postCost: 86216,
    postDealDone: false,
    postImage: null,
    postTitle: 'nostrud eiusmod',
    statuss: 0,
    townID: 1,
    updated: '2022-07-31T01:21:18.791Z',
    categoryID: 54,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-03-28T21:07:39.128Z',
    postContent:
      'Dolor non sunt Lorem esse aute. Nisi irure pariatur incididunt commodo esse sint eiusmod nostrud anim commodo nisi do ipsum.',
    postCost: 98282,
    postDealDone: false,
    postImage: null,
    postTitle: 'fugiat quis',
    statuss: 1,
    townID: 11,
    updated: '2021-02-11T04:59:03.680Z',
    categoryID: 35,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2014-06-11T01:07:55.164Z',
    postContent:
      'Deserunt dolor ad cillum nostrud. Eu consequat fugiat magna est tempor aute laborum.',
    postCost: 53782,
    postDealDone: false,
    postImage: null,
    postTitle: 'commodo laborum',
    statuss: 0,
    townID: 19,
    updated: '2020-12-12T01:05:59.481Z',
    categoryID: 168,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2010-09-19T20:10:58.063Z',
    postContent:
      'Ipsum nulla cillum pariatur velit id fugiat mollit. Dolore quis reprehenderit pariatur duis quis aute aliqua occaecat non aute.',
    postCost: 15371,
    postDealDone: false,
    postImage: null,
    postTitle: 'elit reprehenderit',
    statuss: 1,
    townID: 15,
    updated: '2016-08-10T05:35:23.171Z',
    categoryID: 38,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2013-08-16T16:29:49.573Z',
    postContent:
      'Sit irure nulla cillum enim laboris sint mollit magna duis laborum eiusmod. Ex occaecat pariatur irure culpa amet amet consequat.',
    postCost: 90122,
    postDealDone: true,
    postImage: null,
    postTitle: 'mollit aute',
    statuss: 0,
    townID: 3,
    updated: '2018-07-29T00:19:58.786Z',
    categoryID: 158,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2012-04-26T20:28:56.288Z',
    postContent:
      'Commodo nisi veniam est eiusmod Lorem proident voluptate ullamco fugiat fugiat. Lorem duis ipsum sint proident excepteur est nostrud.',
    postCost: 46863,
    postDealDone: false,
    postImage: null,
    postTitle: 'est ea',
    statuss: 0,
    townID: 9,
    updated: '2021-01-14T12:38:48.034Z',
    categoryID: 75,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2010-07-02T14:07:14.174Z',
    postContent:
      'Enim non laborum quis dolor officia. Ea qui labore reprehenderit eu consequat sint sunt fugiat consectetur ex.',
    postCost: 6422,
    postDealDone: true,
    postImage: null,
    postTitle: 'nulla exercitation',
    statuss: 0,
    townID: 12,
    updated: '2017-04-15T07:57:17.626Z',
    categoryID: 179,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2013-02-13T05:00:18.532Z',
    postContent:
      'Mollit excepteur labore eu sunt ad cillum do velit dolor duis id id. Proident nisi est enim incididunt ea cupidatat esse culpa id quis minim est sint.',
    postCost: 38749,
    postDealDone: false,
    postImage: null,
    postTitle: 'laboris ex',
    statuss: 1,
    townID: 7,
    updated: '2018-10-15T04:50:30.775Z',
    categoryID: 22,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-09-15T02:48:15.857Z',
    postContent:
      'Nostrud duis ad excepteur cillum ea nostrud cillum aliquip enim mollit do amet. Eu nisi ut sit nostrud anim.',
    postCost: 76610,
    postDealDone: false,
    postImage: null,
    postTitle: 'nostrud labore',
    statuss: 1,
    townID: 19,
    updated: '2019-04-02T08:57:57.858Z',
    categoryID: 105,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-09-01T00:30:42.318Z',
    postContent:
      'Ea aute est incididunt duis laborum non nostrud reprehenderit incididunt. Eu esse sint enim duis tempor adipisicing labore adipisicing elit fugiat excepteur.',
    postCost: 85287,
    postDealDone: true,
    postImage: null,
    postTitle: 'enim sunt',
    statuss: 1,
    townID: 8,
    updated: '2016-07-07T07:28:40.005Z',
    categoryID: 2,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2012-11-28T04:18:48.737Z',
    postContent:
      'In fugiat dolor magna do. Culpa aliqua aliqua dolore eiusmod labore minim tempor incididunt.',
    postCost: 77598,
    postDealDone: true,
    postImage: null,
    postTitle: 'incididunt sint',
    statuss: 0,
    townID: 20,
    updated: '2021-05-26T07:09:21.311Z',
    categoryID: 91,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2013-10-30T06:25:41.368Z',
    postContent:
      'Laboris consectetur consectetur reprehenderit consequat magna proident ad in qui magna velit Lorem esse officia. Irure aliqua voluptate exercitation elit sunt elit nostrud labore.',
    postCost: 74872,
    postDealDone: true,
    postImage: null,
    postTitle: 'qui laborum',
    statuss: 0,
    townID: 4,
    updated: '2020-06-03T13:34:41.776Z',
    categoryID: 78,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-06-03T18:06:16.218Z',
    postContent:
      'Aliquip ut et exercitation veniam nostrud anim nulla eiusmod. Ad laboris et velit sunt eu exercitation amet dolor excepteur incididunt est.',
    postCost: 94833,
    postDealDone: true,
    postImage: null,
    postTitle: 'consequat Lorem',
    statuss: 0,
    townID: 3,
    updated: '2017-08-04T01:12:50.150Z',
    categoryID: 70,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2013-09-28T09:44:31.167Z',
    postContent:
      'Quis culpa enim excepteur enim nostrud culpa quis et laboris ad eu Lorem irure amet. Laboris proident nostrud qui qui elit excepteur dolor deserunt enim enim excepteur aute laboris.',
    postCost: 42202,
    postDealDone: true,
    postImage: null,
    postTitle: 'mollit ut',
    statuss: 0,
    townID: 5,
    updated: '2018-08-01T07:32:00.729Z',
    categoryID: 177,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2013-10-02T00:05:49.561Z',
    postContent:
      'Id sunt reprehenderit excepteur quis laboris culpa non culpa et deserunt adipisicing incididunt sit. Ex cillum nostrud ut dolore exercitation ipsum.',
    postCost: 39019,
    postDealDone: true,
    postImage: null,
    postTitle: 'veniam ipsum',
    statuss: 0,
    townID: 8,
    updated: '2020-12-17T15:22:34.517Z',
    categoryID: 94,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-10-12T22:31:05.030Z',
    postContent:
      'In laboris cupidatat labore exercitation dolore anim. Dolore nulla cillum laborum sunt Lorem consectetur commodo reprehenderit nulla mollit et non id exercitation.',
    postCost: 12401,
    postDealDone: false,
    postImage: null,
    postTitle: 'nulla in',
    statuss: 1,
    townID: 20,
    updated: '2017-04-23T14:55:03.180Z',
    categoryID: 87,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2012-05-30T16:46:26.052Z',
    postContent:
      'Proident in in laboris do dolore qui consectetur. Amet irure aliquip consectetur quis do irure ad commodo duis ut exercitation velit aliqua.',
    postCost: 14267,
    postDealDone: false,
    postImage: null,
    postTitle: 'sint non',
    statuss: 0,
    townID: 4,
    updated: '2019-11-29T04:55:02.000Z',
    categoryID: 24,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2011-01-04T10:51:04.381Z',
    postContent:
      'Elit reprehenderit velit ex exercitation ipsum excepteur eu aute consectetur esse ex laboris sit. Excepteur irure laboris exercitation incididunt deserunt mollit dolore ad dolor.',
    postCost: 55570,
    postDealDone: true,
    postImage: null,
    postTitle: 'velit sunt',
    statuss: 0,
    townID: 2,
    updated: '2019-12-27T16:11:45.256Z',
    categoryID: 25,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2011-02-26T08:23:59.768Z',
    postContent:
      'Anim aute labore ullamco exercitation ut. Velit ullamco labore labore reprehenderit irure magna cupidatat nulla ad id enim cillum deserunt ut.',
    postCost: 25295,
    postDealDone: false,
    postImage: null,
    postTitle: 'do exercitation',
    statuss: 1,
    townID: 15,
    updated: '2020-09-07T20:40:48.278Z',
    categoryID: 113,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2014-02-20T17:11:18.010Z',
    postContent:
      'Consequat consequat proident non non culpa duis ullamco irure eu ut aute quis. Ea ad officia ad aliquip consequat cupidatat Lorem sint qui mollit et enim proident consequat.',
    postCost: 39502,
    postDealDone: true,
    postImage: null,
    postTitle: 'ut nostrud',
    statuss: 0,
    townID: 1,
    updated: '2020-05-02T19:21:00.178Z',
    categoryID: 43,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2014-06-15T18:36:52.993Z',
    postContent:
      'Et ex laboris magna veniam irure magna nostrud deserunt irure et. Excepteur veniam non id exercitation ullamco deserunt consequat aute elit consectetur.',
    postCost: 88065,
    postDealDone: true,
    postImage: null,
    postTitle: 'dolore do',
    statuss: 1,
    townID: 12,
    updated: '2020-07-03T12:01:08.663Z',
    categoryID: 43,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-02-01T16:54:58.900Z',
    postContent:
      'Fugiat consequat id culpa esse laborum. Sint Lorem proident ad voluptate labore nisi proident enim excepteur enim.',
    postCost: 77456,
    postDealDone: true,
    postImage: null,
    postTitle: 'laboris ad',
    statuss: 0,
    townID: 4,
    updated: '2021-08-31T08:13:58.671Z',
    categoryID: 137,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2012-08-17T01:53:47.568Z',
    postContent:
      'Anim nulla fugiat officia laboris. Magna id laboris consequat cillum elit dolore adipisicing consectetur quis reprehenderit cupidatat laborum quis ex.',
    postCost: 64247,
    postDealDone: false,
    postImage: null,
    postTitle: 'do cupidatat',
    statuss: 0,
    townID: 11,
    updated: '2022-11-17T12:53:05.068Z',
    categoryID: 96,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-02-28T09:29:09.599Z',
    postContent:
      'Laborum laboris dolore in adipisicing tempor veniam eiusmod ex incididunt sunt aliquip. Excepteur cupidatat do ex consectetur elit nulla incididunt veniam nostrud duis qui.',
    postCost: 14154,
    postDealDone: false,
    postImage: null,
    postTitle: 'commodo enim',
    statuss: 1,
    townID: 12,
    updated: '2016-10-07T00:26:16.752Z',
    categoryID: 28,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2013-09-22T18:41:19.679Z',
    postContent:
      'Nisi laboris proident amet anim aliqua laborum ad occaecat pariatur est fugiat anim. Reprehenderit culpa occaecat veniam nostrud amet.',
    postCost: 44260,
    postDealDone: false,
    postImage: null,
    postTitle: 'quis adipisicing',
    statuss: 1,
    townID: 9,
    updated: '2016-01-21T19:31:44.613Z',
    categoryID: 134,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2012-06-03T02:32:09.680Z',
    postContent:
      'Anim aliquip labore voluptate aliqua consequat cillum minim qui. Exercitation esse ex magna dolor dolore Lorem ea irure aute in aute laboris aliquip.',
    postCost: 64921,
    postDealDone: false,
    postImage: null,
    postTitle: 'quis consectetur',
    statuss: 1,
    townID: 20,
    updated: '2020-07-10T23:35:08.737Z',
    categoryID: 60,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-06-10T09:23:44.197Z',
    postContent:
      'Sunt cupidatat labore cupidatat id in voluptate excepteur cillum elit sit quis Lorem elit voluptate. Est consectetur esse enim sunt ad do exercitation id velit pariatur id labore amet ut.',
    postCost: 55880,
    postDealDone: true,
    postImage: null,
    postTitle: 'adipisicing excepteur',
    statuss: 1,
    townID: 1,
    updated: '2017-08-16T23:51:42.431Z',
    categoryID: 5,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2014-03-05T20:14:21.814Z',
    postContent:
      'Et cupidatat incididunt ut anim elit tempor aliqua. Irure occaecat aliqua eiusmod officia exercitation.',
    postCost: 17861,
    postDealDone: false,
    postImage: null,
    postTitle: 'mollit duis',
    statuss: 1,
    townID: 2,
    updated: '2016-08-22T16:29:31.698Z',
    categoryID: 21,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2010-07-29T18:30:39.481Z',
    postContent:
      'Ex reprehenderit qui eu ut nulla elit magna do nulla quis cillum quis adipisicing. Dolore mollit ut exercitation exercitation adipisicing dolore duis elit laboris mollit laboris non excepteur.',
    postCost: 63671,
    postDealDone: true,
    postImage: null,
    postTitle: 'et cillum',
    statuss: 0,
    townID: 3,
    updated: '2016-05-07T06:49:37.032Z',
    categoryID: 140,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2012-04-03T19:46:22.054Z',
    postContent:
      'Adipisicing et nisi ex nostrud qui fugiat cillum consequat. Occaecat et et dolore esse mollit nostrud ullamco commodo.',
    postCost: 94721,
    postDealDone: true,
    postImage: null,
    postTitle: 'exercitation dolor',
    statuss: 1,
    townID: 13,
    updated: '2016-02-17T10:56:34.872Z',
    categoryID: 33,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2011-05-24T07:40:27.257Z',
    postContent:
      'Magna proident incididunt officia voluptate in laboris deserunt. Et ipsum ea aute consequat mollit fugiat excepteur.',
    postCost: 97735,
    postDealDone: false,
    postImage: null,
    postTitle: 'aliquip dolore',
    statuss: 1,
    townID: 19,
    updated: '2018-04-20T19:50:44.529Z',
    categoryID: 132,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2012-07-15T10:26:34.331Z',
    postContent:
      'Consectetur sunt esse elit sit ullamco officia ea culpa. Veniam id sit culpa labore aute amet minim incididunt laborum eu irure.',
    postCost: 37926,
    postDealDone: true,
    postImage: null,
    postTitle: 'magna sit',
    statuss: 0,
    townID: 18,
    updated: '2017-07-10T16:28:59.165Z',
    categoryID: 28,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2011-08-13T00:48:49.196Z',
    postContent:
      'Commodo duis aliqua occaecat aliqua veniam ad ipsum culpa et elit esse eiusmod. Nulla labore id excepteur duis sunt quis excepteur tempor sint proident commodo.',
    postCost: 85542,
    postDealDone: false,
    postImage: null,
    postTitle: 'fugiat nostrud',
    statuss: 0,
    townID: 7,
    updated: '2016-03-15T09:41:35.479Z',
    categoryID: 91,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2014-10-12T17:14:24.358Z',
    postContent:
      'Eu eu velit amet aliquip officia pariatur et minim nisi exercitation ea exercitation nulla. Labore nisi enim anim esse laboris.',
    postCost: 92708,
    postDealDone: true,
    postImage: null,
    postTitle: 'culpa nulla',
    statuss: 1,
    townID: 12,
    updated: '2022-01-17T18:34:08.288Z',
    categoryID: 68,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-03-01T01:40:26.524Z',
    postContent:
      'Commodo pariatur ex deserunt eiusmod nostrud id magna consequat proident. Incididunt cupidatat incididunt ut esse occaecat tempor dolor minim minim tempor tempor esse.',
    postCost: 66357,
    postDealDone: true,
    postImage: null,
    postTitle: 'cupidatat irure',
    statuss: 1,
    townID: 5,
    updated: '2017-01-17T16:27:07.102Z',
    categoryID: 115,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2010-09-17T06:36:49.119Z',
    postContent:
      'Occaecat fugiat minim eu fugiat dolor consequat et cupidatat excepteur dolore sit aliqua. Ut dolore cillum occaecat ea elit officia magna cillum exercitation.',
    postCost: 2878,
    postDealDone: true,
    postImage: null,
    postTitle: 'anim mollit',
    statuss: 1,
    townID: 19,
    updated: '2018-11-28T16:32:06.651Z',
    categoryID: 183,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2013-01-01T17:02:33.463Z',
    postContent:
      'Et Lorem proident consequat tempor anim excepteur labore culpa laborum duis. Esse laborum culpa ad labore dolor.',
    postCost: 80384,
    postDealDone: false,
    postImage: null,
    postTitle: 'do est',
    statuss: 1,
    townID: 8,
    updated: '2021-03-10T07:03:06.808Z',
    categoryID: 127,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2013-12-21T05:30:30.951Z',
    postContent:
      'Aliquip fugiat id proident fugiat enim et do minim id cupidatat magna esse quis. Excepteur anim enim reprehenderit cupidatat do in in qui exercitation mollit ut ullamco.',
    postCost: 90590,
    postDealDone: false,
    postImage: null,
    postTitle: 'ad quis',
    statuss: 0,
    townID: 19,
    updated: '2020-05-17T20:51:26.471Z',
    categoryID: 21,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2013-09-23T00:22:18.425Z',
    postContent:
      'Labore eu sit sint sint. Do velit ullamco aliquip deserunt adipisicing.',
    postCost: 90540,
    postDealDone: false,
    postImage: null,
    postTitle: 'irure ut',
    statuss: 1,
    townID: 9,
    updated: '2022-09-16T21:25:51.896Z',
    categoryID: 140,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2010-03-24T21:01:57.155Z',
    postContent:
      'Veniam cillum fugiat cupidatat duis. Qui in aliquip pariatur dolore laborum dolor.',
    postCost: 35496,
    postDealDone: false,
    postImage: null,
    postTitle: 'ad excepteur',
    statuss: 1,
    townID: 18,
    updated: '2016-03-07T20:35:03.389Z',
    categoryID: 88,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-03-21T07:47:19.308Z',
    postContent:
      'Proident reprehenderit duis et velit occaecat. Veniam Lorem laboris aute ut est culpa.',
    postCost: 4114,
    postDealDone: false,
    postImage: null,
    postTitle: 'amet amet',
    statuss: 0,
    townID: 12,
    updated: '2022-11-21T11:43:34.838Z',
    categoryID: 28,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2011-05-02T11:39:23.065Z',
    postContent:
      'Adipisicing id magna do fugiat. Cillum consequat pariatur ut cupidatat aliqua irure veniam ad voluptate nisi ullamco anim minim minim.',
    postCost: 17525,
    postDealDone: true,
    postImage: null,
    postTitle: 'proident officia',
    statuss: 0,
    townID: 6,
    updated: '2016-03-28T08:52:20.447Z',
    categoryID: 179,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2012-01-07T22:50:32.169Z',
    postContent:
      'Amet incididunt culpa Lorem veniam irure mollit non sint amet eiusmod. Amet do non qui amet id.',
    postCost: 25414,
    postDealDone: true,
    postImage: null,
    postTitle: 'consequat ullamco',
    statuss: 1,
    townID: 14,
    updated: '2022-11-30T15:01:32.326Z',
    categoryID: 46,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2014-08-11T09:23:36.360Z',
    postContent:
      'Labore in proident eiusmod in dolor irure. Commodo tempor mollit aute exercitation aliquip reprehenderit proident.',
    postCost: 30278,
    postDealDone: true,
    postImage: null,
    postTitle: 'dolore aliqua',
    statuss: 1,
    townID: 2,
    updated: '2020-11-04T15:48:45.384Z',
    categoryID: 102,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-10-14T18:32:30.883Z',
    postContent:
      'Aliqua Lorem adipisicing elit pariatur magna dolor mollit proident est fugiat voluptate. Laborum veniam ex quis in in exercitation.',
    postCost: 90344,
    postDealDone: true,
    postImage: null,
    postTitle: 'et reprehenderit',
    statuss: 0,
    townID: 12,
    updated: '2016-09-05T06:22:24.472Z',
    categoryID: 51,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-09-29T04:42:02.942Z',
    postContent:
      'Pariatur est occaecat reprehenderit tempor. Duis deserunt cillum mollit non id dolor nisi nisi duis consequat fugiat duis deserunt.',
    postCost: 88553,
    postDealDone: true,
    postImage: null,
    postTitle: 'consequat Lorem',
    statuss: 1,
    townID: 3,
    updated: '2018-03-19T22:18:01.253Z',
    categoryID: 88,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2012-03-23T18:35:52.514Z',
    postContent:
      'Lorem enim sint cillum veniam sunt. Aliqua sunt ut adipisicing irure incididunt culpa anim deserunt irure elit qui ea.',
    postCost: 44747,
    postDealDone: false,
    postImage: null,
    postTitle: 'ad officia',
    statuss: 0,
    townID: 5,
    updated: '2022-02-24T23:16:27.862Z',
    categoryID: 125,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2012-11-11T21:28:45.227Z',
    postContent:
      'Irure minim ad non reprehenderit aute tempor voluptate Lorem. Occaecat mollit eiusmod in in magna enim minim.',
    postCost: 32066,
    postDealDone: false,
    postImage: null,
    postTitle: 'minim labore',
    statuss: 0,
    townID: 17,
    updated: '2019-10-13T01:15:32.493Z',
    categoryID: 132,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2010-04-11T01:36:05.266Z',
    postContent:
      'Ullamco ex voluptate esse aliqua Lorem eu deserunt sunt nulla exercitation. Pariatur aliquip minim labore laboris id in ipsum deserunt ipsum pariatur nisi cupidatat.',
    postCost: 84310,
    postDealDone: true,
    postImage: null,
    postTitle: 'veniam cupidatat',
    statuss: 1,
    townID: 15,
    updated: '2017-08-09T12:23:45.055Z',
    categoryID: 133,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2010-06-06T09:33:48.472Z',
    postContent:
      'Nostrud aliqua nisi qui anim voluptate elit veniam dolor non aliqua sunt ad aute duis. In minim dolor dolor velit ex tempor incididunt sunt tempor ipsum.',
    postCost: 32422,
    postDealDone: true,
    postImage: null,
    postTitle: 'voluptate exercitation',
    statuss: 1,
    townID: 12,
    updated: '2020-02-04T20:24:27.667Z',
    categoryID: 14,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2013-03-10T19:23:10.819Z',
    postContent:
      'Exercitation commodo ut ut incididunt culpa duis dolore in commodo quis mollit incididunt eu. Aliquip id fugiat occaecat sit pariatur nulla dolor eiusmod adipisicing Lorem.',
    postCost: 9699,
    postDealDone: false,
    postImage: null,
    postTitle: 'occaecat consequat',
    statuss: 1,
    townID: 19,
    updated: '2021-09-27T07:54:17.611Z',
    categoryID: 111,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-03-01T08:17:11.924Z',
    postContent:
      'Duis voluptate consequat adipisicing dolore. Ullamco elit nostrud fugiat cupidatat minim culpa.',
    postCost: 53016,
    postDealDone: true,
    postImage: null,
    postTitle: 'in do',
    statuss: 0,
    townID: 4,
    updated: '2017-07-26T04:02:14.663Z',
    categoryID: 3,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2012-01-23T13:35:24.681Z',
    postContent:
      'Minim nulla labore non ipsum velit. Nisi anim proident ut labore reprehenderit nostrud laborum id amet velit ullamco officia nisi.',
    postCost: 13810,
    postDealDone: true,
    postImage: null,
    postTitle: 'dolore nulla',
    statuss: 0,
    townID: 5,
    updated: '2018-02-13T10:59:52.896Z',
    categoryID: 109,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2012-04-05T15:40:20.427Z',
    postContent:
      'Incididunt ex consequat reprehenderit officia nostrud deserunt nulla commodo aliqua. Excepteur sunt enim ex laboris dolore ea deserunt officia sint nisi.',
    postCost: 45774,
    postDealDone: true,
    postImage: null,
    postTitle: 'do id',
    statuss: 1,
    townID: 2,
    updated: '2019-03-20T20:09:11.571Z',
    categoryID: 178,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2010-01-23T04:22:26.903Z',
    postContent:
      'Lorem do quis est dolore adipisicing ullamco ipsum nostrud. Enim aliqua aliquip eu est eiusmod eu sit enim.',
    postCost: 82605,
    postDealDone: false,
    postImage: null,
    postTitle: 'aliquip aliquip',
    statuss: 1,
    townID: 3,
    updated: '2019-08-03T06:45:08.468Z',
    categoryID: 141,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2014-07-22T01:10:27.141Z',
    postContent:
      'Occaecat do eu esse excepteur amet consectetur nisi excepteur qui dolor do cillum. In fugiat do aute et fugiat culpa do dolore voluptate exercitation cupidatat laboris ut.',
    postCost: 91616,
    postDealDone: true,
    postImage: null,
    postTitle: 'enim elit',
    statuss: 0,
    townID: 2,
    updated: '2017-07-20T11:22:47.243Z',
    categoryID: 166,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2014-06-26T01:42:04.583Z',
    postContent:
      'Id pariatur ipsum minim eu commodo. Veniam velit officia qui sint qui eu adipisicing magna.',
    postCost: 13794,
    postDealDone: false,
    postImage: null,
    postTitle: 'sint ex',
    statuss: 0,
    townID: 17,
    updated: '2016-12-25T14:05:48.573Z',
    categoryID: 96,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2010-08-29T13:49:47.985Z',
    postContent:
      'Mollit duis quis magna velit nulla pariatur ipsum proident labore cupidatat non proident eiusmod ea. Fugiat id consectetur adipisicing Lorem voluptate aliqua occaecat ad Lorem irure ipsum.',
    postCost: 86136,
    postDealDone: true,
    postImage: null,
    postTitle: 'excepteur ad',
    statuss: 1,
    townID: 18,
    updated: '2022-11-17T03:56:52.396Z',
    categoryID: 3,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2011-06-22T04:51:16.126Z',
    postContent:
      'Laboris minim incididunt eu enim. Elit voluptate aute fugiat ea non ut tempor amet ut cillum eu ipsum proident.',
    postCost: 42229,
    postDealDone: false,
    postImage: null,
    postTitle: 'fugiat magna',
    statuss: 0,
    townID: 9,
    updated: '2017-04-29T01:16:57.526Z',
    categoryID: 121,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2014-10-04T02:22:13.714Z',
    postContent:
      'Eu laboris aute culpa magna cupidatat eu. Id dolor irure in nostrud nisi cillum dolore proident in magna.',
    postCost: 65378,
    postDealDone: false,
    postImage: null,
    postTitle: 'amet magna',
    statuss: 1,
    townID: 12,
    updated: '2016-07-20T02:19:29.600Z',
    categoryID: 164,
    userTableID: 1,
  },
  {
    postID: null,
    created: '2011-05-03T18:57:38.831Z',
    postContent:
      'Sit cupidatat sunt ipsum amet mollit proident eu commodo ea nostrud. Dolore labore exercitation adipisicing id eu cillum irure irure ut.',
    postCost: 35446,
    postDealDone: false,
    postImage: null,
    postTitle: 'incididunt elit',
    statuss: 0,
    townID: 17,
    updated: '2017-03-17T10:12:46.163Z',
    categoryID: 90,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2010-09-07T21:10:10.865Z',
    postContent:
      'Esse elit non mollit proident eu non sit fugiat. Do do cupidatat laboris aliqua eu commodo sunt dolore veniam do sunt consequat exercitation sunt.',
    postCost: 15953,
    postDealDone: false,
    postImage: null,
    postTitle: 'ex veniam',
    statuss: 1,
    townID: 8,
    updated: '2020-11-26T15:01:35.262Z',
    categoryID: 53,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2010-07-21T21:59:48.275Z',
    postContent:
      'Magna anim est commodo proident labore duis minim sint sint sunt aute. Irure voluptate nisi magna sit commodo nulla Lorem qui amet ullamco.',
    postCost: 14694,
    postDealDone: false,
    postImage: null,
    postTitle: 'ex enim',
    statuss: 0,
    townID: 2,
    updated: '2021-02-26T14:33:36.018Z',
    categoryID: 72,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2012-11-12T20:07:48.837Z',
    postContent:
      'Elit aliquip reprehenderit elit fugiat commodo occaecat incididunt. Nostrud enim mollit aliquip do duis ut adipisicing eu est et exercitation proident.',
    postCost: 65496,
    postDealDone: false,
    postImage: null,
    postTitle: 'nulla cupidatat',
    statuss: 0,
    townID: 20,
    updated: '2018-09-28T11:05:36.793Z',
    categoryID: 173,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2014-06-15T11:02:41.164Z',
    postContent:
      'Voluptate ut sunt sunt dolor dolor occaecat velit reprehenderit officia velit. Est ipsum mollit commodo exercitation consectetur non voluptate et anim nostrud fugiat consequat esse.',
    postCost: 54878,
    postDealDone: true,
    postImage: null,
    postTitle: 'labore quis',
    statuss: 1,
    townID: 19,
    updated: '2020-09-27T18:56:26.808Z',
    categoryID: 17,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2010-11-06T09:28:47.062Z',
    postContent:
      'Eiusmod esse elit nulla proident anim culpa id eu. Aliquip amet excepteur est commodo et fugiat et esse adipisicing nulla reprehenderit consequat voluptate.',
    postCost: 96379,
    postDealDone: true,
    postImage: null,
    postTitle: 'dolore pariatur',
    statuss: 1,
    townID: 12,
    updated: '2016-08-12T08:10:12.480Z',
    categoryID: 26,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2012-08-14T03:55:46.566Z',
    postContent:
      'Est sit et et cillum reprehenderit velit ex. Velit ullamco mollit enim esse occaecat veniam et cupidatat.',
    postCost: 19747,
    postDealDone: false,
    postImage: null,
    postTitle: 'dolore tempor',
    statuss: 1,
    townID: 4,
    updated: '2016-11-10T19:10:37.683Z',
    categoryID: 182,
    userTableID: 2,
  },
  {
    postID: null,
    created: '2014-10-16T18:21:52.674Z',
    postContent:
      'Minim sunt id pariatur sunt deserunt consequat elit cillum labore pariatur amet. Sint voluptate tempor exercitation tempor aute reprehenderit mollit labore ullamco nostrud eu.',
    postCost: 60775,
    postDealDone: false,
    postImage: null,
    postTitle: 'incididunt incididunt',
    statuss: 1,
    townID: 14,
    updated: '2020-11-19T05:59:19.492Z',
    categoryID: 20,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2011-02-07T23:23:09.444Z',
    postContent:
      'Deserunt cupidatat dolore esse quis elit deserunt veniam velit enim pariatur cupidatat irure voluptate ea. Aute elit ullamco pariatur ullamco quis deserunt duis duis reprehenderit enim dolor mollit esse.',
    postCost: 93316,
    postDealDone: true,
    postImage: null,
    postTitle: 'incididunt velit',
    statuss: 1,
    townID: 7,
    updated: '2016-03-20T20:41:07.396Z',
    categoryID: 84,
    userTableID: 3,
  },
  {
    postID: null,
    created: '2011-07-12T04:06:01.347Z',
    postContent:
      'Duis culpa proident mollit nostrud. Occaecat proident duis nostrud culpa incididunt pariatur nulla et sit est culpa enim tempor dolor.',
    postCost: 49152,
    postDealDone: false,
    postImage: null,
    postTitle: 'exercitation id',
    statuss: 0,
    townID: 19,
    updated: '2019-05-15T06:34:01.000Z',
    categoryID: 162,
    userTableID: 4,
  },
  {
    postID: null,
    created: '2012-07-22T17:55:06.872Z',
    postContent:
      'Excepteur laboris laborum amet incididunt amet quis laborum elit. Mollit eu irure veniam consectetur occaecat ea officia.',
    postCost: 95921,
    postDealDone: true,
    postImage: null,
    postTitle: 'mollit ea',
    statuss: 0,
    townID: 5,
    updated: '2018-03-11T19:46:25.403Z',
    categoryID: 26,
    userTableID: 3,
  },
];

export const postCreateSet = (post) => {
  const formdata = new FormData();
  formdata.append('postID', post.postID);
  formdata.append('created', post.created);
  formdata.append('postContent', post.postContent);
  formdata.append('postCost', post.postCost);
  formdata.append('postDealDone', post.postDealDone);
  formdata.append('postImage', post.postImage);
  formdata.append('postTitle', post.postTitle);
  formdata.append('statuss', post.statuss);
  formdata.append('townID', post.townID);
  formdata.append('updated', post.updated);
  formdata.append('category', post.categoryID);
  formdata.append('user', post.userTableID);
  return formdata;
};

export const postMade = () => {
  for (var n = 0; n < 100; n++) {
    posts[n].postID = n + 1;
    posts[n].created = posts[n].created.replace('T', ' ');
    posts[n].created = posts[n].created
      .replace(/\.[0-9][0-9][0-9]+Z/gi, '')
      .toString();
    posts[n].updated = posts[n].updated.replace('T', ' ');
    posts[n].updated = posts[n].updated
      .replace(/\.[0-9][0-9][0-9]+Z/gi, '')
      .toString();
    createPost(postCreateSet(posts[n]));
  }
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
