export const Routes = {
  SIGN_IN_SCREEN: 'SignInScreen',
  SIGN_UP_SCREEN: 'SignUpScreen',
  MAIN_SCREEN: 'MainScreen',
  CONTENT_TAB: 'ContentTab',
  LIST_SCREEN: 'ListScreen',
  NEARME_SCREEN: 'NearMeScreen',
  CHAT_LIST_SCREEN: 'ChatListScreen',
  CHAT_SCREEN: 'ChatScreen',
  ALERT_SCREEN: 'AlertScreen',
  MY_SCREEN: 'MyScreen',
  FAVORITE_ITEM_SCREEN: 'FavoriteItemScreen',
  DETAIL_ITEM_SCREEN: 'DetailItemScreen',
  EDIT_ITEM_SCREEN: 'EditItemScreen',
  NEW_ITEM_SCREEN: 'NewItemScreen',
  SEARCH_SCREEN: 'SearchScreen',
  IMAGE_PICKER: 'ImagePicker',
  DEAL_LOG_SCREEN: 'DealLogScreen',
  PURCHASE_LOG_SCREEN: 'PurchaseLogScreen',
  NEW_POST_SCREEN: 'NewPostScreen',
  CATEGORY_SCREEN:'CategoryScreen',
  CHART_SCREEN:'ChartScreen',
};
